pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_DAMAGE_CHARGE_MULTIPLIER: i32 = 0x4D;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_ARMOR_CHARGE_MULTIPLIER: i32 = 0x4E;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CHARGE_START: i32 = 0x4F;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CHARGE_END: i32 = 0x50;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CURRENT_DAMAGE: i32 = 0x51;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_INT_CHARGE_FRAME: i32 = 0x100000C0;