pub const FIGHTER_BAYONETTA_STATUS_KIND_ATTACK_AIR_F_DASH: i32 = 0x1F3;
pub const FIGHTER_BAYONETTA_STATUS_KIND_ATTACK_AIR_F_SMASH: i32 = 0x1F4;
pub const FIGHTER_BAYONETTA_STATUS_KIND_ATTACK_AIR_U_SMASH: i32 = 0x1F5;
pub const FIGHTER_BAYONETTA_STATUS_KIND_ATTACK_AIR_D_SMASH: i32 = 0x1F6;