pub const FIGHTER_CHROM_INSTANCE_WORK_ID_FLAG_SPECIAL_S_ATTACK: i32 = 0x200000E2;
pub const FIGHTER_CHROM_INSTANCE_WORK_ID_INT_SPECIAL_LW_HIT_COUNT: i32 = 0x100000CC;
pub const FIGHTER_CHROM_STATUS_KIND_SPECIAL_S_ATTACK: i32 = 0x1F3;
pub const FIGHTER_CHROM_STATUS_KIND_SPECIAL_HI_HOLD: i32 = 0x1F4;
pub const FIGHTER_CHROM_STATUS_KIND_SPECIAL_HI_DROP: i32 = 0x1F5;
pub const FIGHTER_CHROM_STATUS_KIND_SPECIAL_HI_LAND: i32 = 0x1F6;