//Custom Universal Consts
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALL_LAST_STOCK: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000116); //Indicates all fighters are on their last stock
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALREADY_BOUNCED: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000117); //Tracks if the ball has bounced at least once since being thrown
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ASDI_START: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000118);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_CONTINUE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000119);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_FALL: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011A);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_LANDING: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011B);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_GRAVITY: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011C);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_GRAVITY_ENABLED: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011D);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_BOUNCE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011E);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_ADD: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000011F);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_GATLING: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000120);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000121);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED_PREVENT: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000122);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DID_MAX_JUMP_COUNT: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000123);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FINAL_ZOOM_LAST_STOCK: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000124);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FIRST_BOUNCE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000125); //Allows the throwing player to bounce the ball on their own side once
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FULL_SMASH_ATTACK: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000126);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HARD_BREAK_ENABLED: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000127);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HAS_CATCH: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000128);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_IS_CC: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000129);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_PERFECT_WAVEDASH: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012A);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_READY_GO: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012B); //Returns false for exactly one frame after is_ready_go becomes true, used to initiate certain events exactly once at the start of a match
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_DISABLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012C);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_DISABLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012D);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_N_DISABLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012E);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_S_DISABLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x2000012F);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_USED_FS: smash::lib::LuaConst = smash::lib::LuaConst::new(0x20000130); //Flags when you just used a Final Smash in Special Smash
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_ATTACK_DASH_FALL_SPEED_Y_MUL: smash::lib::LuaConst = smash::lib::LuaConst::new(0x641);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_JUMP_SPEED_RATIO: smash::lib::LuaConst = smash::lib::LuaConst::new(0x642);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_SMASH_ATTACK_CHARGE_FRAME: smash::lib::LuaConst = smash::lib::LuaConst::new(0x643);
pub const FIGHTER_INSTANCE_WORK_ID_INT_ATTACK_ANGLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000ED);
pub const FIGHTER_INSTANCE_WORK_ID_INT_CLIFF_ID: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000EE);
pub const FIGHTER_INSTANCE_WORK_ID_INT_COMMAND_INPUT_TIMER: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000EF);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FINAL_ZOOM_COUNTER: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F0);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FINAL_ZOOM_HANDLE: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F1);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FULL_HOP_ENABLE_DELAY: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F2);
pub const FIGHTER_INSTANCE_WORK_ID_INT_GOT_HIT: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F3); //Tracks if a player got hit during One-Hit mode
pub const FIGHTER_INSTANCE_WORK_ID_INT_MASHING: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F4);
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRIED: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F5);
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRY_TIMER: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F6);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_BREAK_TIMER: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F7);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_EFFECT_ID: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F8);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SPECIAL_ZOOM_GFX: smash::lib::LuaConst = smash::lib::LuaConst::new(0x100000F9);
pub const FIGHTER_STATUS_KIND_SPECIAL_GUARD: smash::lib::LuaConst = smash::lib::LuaConst::new(0x644);