pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLAG_CAN_BOUND: i32 = 0x200000E3;
pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_N: i32 = 0x200000E4;
pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLOAT_BOUND_ANGLE: i32 = 0x4D;
pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLOAT_X_CHECK: i32 = 0x4E;
pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLOAT_Y_CHECK: i32 = 0x4F;
pub const FIGHTER_IKE_GENERATE_ARTICLE_SLASH: i32 = 0x1;
pub const WEAPON_IKE_SLASH_STATUS_KIND_SHOOT: i32 = 0x0;
pub const WEAPON_IKE_SLASH_REFLECTOR_KIND_REFLECTOR: i32 = 0x0;