pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_VIS_OFF: i32 = 0x200000E3;
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_VIS_ON: i32 = 0x200000E4;
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_GRAVITY_ON: i32 = 0x200000E5;
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_INPUT_ON: i32 = 0x200000E6;
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLOAT_SPECIAL_LW_POWER: i32 = 0x4B;
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_INT_SPECIAL_LW_EFFECT_COUNT: i32 = 0x100000C0;
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_HI2: i32 = 0x1EE;
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_LW_LOOP: i32 = 0x1EF;