pub const FIGHTER_LUIGI_STATUS_KIND_SPECIAL_LW_LOOP: i32 = 0x1EF;
pub const FIGHTER_LUIGI_STATUS_KIND_SPECIAL_LW_END: i32 = 0x1F0;
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_S_DISCHARGE_CHANCE: i32 = 0x100000C4;
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_LW_THROW_DIRECTION: i32 = 0x100000C5;