pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_DID_ANGLE: i32 = 0x200000E2;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_HI_HI: i32 = 0x1EC;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_HI_F: i32 = 0x1ED;