pub const FIGHTER_METAKNIGHT_GENERATE_ARTICLE_GALAXIA_BEAM: i32 = 0x3;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_S: i32 = 0x200000E5; 
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_STATUS_KIND_SHOOT: i32 = 0x0;