use smash::phx::{
    Vector2f,
    Vector3f
};

pub mod armstrong;
pub mod bayonetta;
pub mod captain;
pub mod chrom;
pub mod consts;
pub mod dedede;
pub mod demon;
pub mod diddy;
pub mod dolly;
pub mod donkey;
pub mod edge;
pub mod element;
pub mod gaogaen;
pub mod gekkouga;
pub mod globals;
pub mod ike;
pub mod ken;
pub mod kirby;
pub mod link;
pub mod littlemac;
pub mod lucas;
pub mod luigi;
pub mod marth;
pub mod metaknight;
pub mod mewtwo;
pub mod miifighter;
pub mod miiswordsman;
pub mod murabito;
pub mod ness;
pub mod palutena;
pub mod pfushigisou;
pub mod pikachu;
pub mod purin;
pub mod reflet;
pub mod robot;
pub mod rockman;
pub mod rosetta;
pub mod roy;
pub mod ryu;
pub mod samusd;
pub mod sheik;
pub mod snake;
pub mod sonic;
pub mod variables;
pub mod wolf;