pub const FIGHTER_PURIN_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_N: i32 = 0x200000E2;
pub const FIGHTER_PURIN_GENERATE_ARTICLE_DISARMING_VOICE: i32 = 0x2;
pub const WEAPON_PURIN_DISARMING_VOICE_STATUS_KIND_SHOOT: i32 = 0x0;