pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_BOOST_GRAVITY: i32 = 0x200000E5;
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE: i32 = 0x100000C1;
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE_DECREASE: i32 = 0x100000C2;
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_EFFECT_COUNTER: i32 = 0x100000C3;
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_FINAL_SMASH_TIMER: i32 = 0x100000C4;
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLOAT_BOOST_SPEED: i32 = 0x4E;
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_BOOST: i32 = 0x1F4;
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_EAGLE: i32 = 0x1F5;
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_ADVENTURE: i32 = 0x1F6;
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_DROP: i32 = 0x1F7;
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_BOUNCE: i32 = 0x1F8;
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_TURN: i32 = 0x9;
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL_START: i32 = 0xA;
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL: i32 = 0xB;
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL_END: i32 = 0xC;

pub const WEAPON_SONIC_SUPERSONIC_INSTANCE_WORK_ID_FLOAT_X_ACCEL: i32 = 0x6;
pub const WEAPON_SONIC_SUPERSONIC_INSTANCE_WORK_ID_FLOAT_Y_ACCEL: i32 = 0x7;