pub const FIGHTER_WARIO_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_HIT: i32 = 0x200000E8;
pub const FIGHTER_WARIO_INSTANCE_WORK_ID_FLAG_SWING_DING_MOVE: i32 = 0x200000E9;
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_LOOP: i32 = 0x201;
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_JUMP_SQUAT: i32 = 0x202;
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_AIR_LOOP: i32 = 0x203;
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_LANDING: i32 = 0x204;
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_END: i32 = 0x205;