use super::*;

/*
First Instance Flag: 0x200000E1
First Instance Float: 0x4D
First Instance Int: 0x100000C0
*/

pub static mut FIGHTER_ARMSTRONG_GENERATE_ARTICLE_FIREPILLAR: i32 = 2;
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_CLEAR_CHARGE: LuaConst = LuaConst::new(0x200000E8);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_SPECIAL_S_RUN: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_SPECIAL_S_JUMP: LuaConst = LuaConst::new(0x200000EA);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_COUNTER_ACTIVE: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_NANOMACHINES: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_FINAL_THROW: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_DAMAGE_CHARGE_MULTIPLIER: LuaConst = LuaConst::new(0x50);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_ARMOR_CHARGE_MULTIPLIER: LuaConst = LuaConst::new(0x51);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CURRENT_DAMAGE: LuaConst = LuaConst::new(0x52);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_INT_CHARGE_FRAME: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_INT_FLAME_PILLAR_ID: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_INT_SPECIAL_S_RUN_TIME: LuaConst = LuaConst::new(0x100000C9);
pub const FIGHTER_ARMSTRONG_STATUS_KIND_SPECIAL_S_RUN: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_ARMSTRONG_STATUS_KIND_SPECIAL_S_END: LuaConst = LuaConst::new(0x1F5);
pub const FIGHTER_ARMSTRONG_STATUS_KIND_FINAL_THROW: LuaConst = LuaConst::new(0x1F6);
pub const WEAPON_ARMSTRONG_FIREPILLAR_STATUS_KIND_BURST: LuaConst = LuaConst::new(0x0);
pub const WEAPON_ARMSTRONG_FIREPILLAR_INSTANCE_WORK_ID_FLOAT_POS_X: LuaConst = LuaConst::new(0x5);
pub const WEAPON_ARMSTRONG_FIREPILLAR_INSTANCE_WORK_ID_FLOAT_POS_Y: LuaConst = LuaConst::new(0x6);
pub const WEAPON_ARMSTRONG_FIREPILLAR_INSTANCE_WORK_ID_INT_EFFECT_ID: LuaConst = LuaConst::new(0x1000000C);