use super::*;

pub const FIGHTER_FALCON_INSTANCE_WORK_ID_FLAG_FALCON_PUNCH_HIT: LuaConst = LuaConst::new(0x200000E3);
pub const FIGHTER_FALCON_INSTANCE_WORK_ID_INT_FALCON_PUNCH_TURN_COUNT: LuaConst = LuaConst::new(0x100000C0);