use super::*;

//Custom Universal Consts
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALL_LAST_STOCK: LuaConst = LuaConst::new(0x20000116); //Indicates all fighters are on their last stock
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALREADY_BOUNCED: LuaConst = LuaConst::new(0x20000117); //Tracks if the ball has bounced at least once since being thrown
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ASDI_START: LuaConst = LuaConst::new(0x20000118);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_CONTINUE: LuaConst = LuaConst::new(0x20000119);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_FALL: LuaConst = LuaConst::new(0x2000011A);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_LANDING: LuaConst = LuaConst::new(0x2000011B);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_GRAVITY: LuaConst = LuaConst::new(0x2000011C);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_GRAVITY_ENABLED: LuaConst = LuaConst::new(0x2000011D);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_BOUNCE: LuaConst = LuaConst::new(0x2000011E);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_ADD: LuaConst = LuaConst::new(0x2000011F);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_GATLING: LuaConst = LuaConst::new(0x20000120);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED: LuaConst = LuaConst::new(0x20000121);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED_PREVENT: LuaConst = LuaConst::new(0x20000122);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DID_MAX_JUMP_COUNT: LuaConst = LuaConst::new(0x20000123);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FINAL_ZOOM_LAST_STOCK: LuaConst = LuaConst::new(0x20000124);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FIRST_BOUNCE: LuaConst = LuaConst::new(0x20000125); //Allows the throwing player to bounce the ball on their own side once
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FULL_SMASH_ATTACK: LuaConst = LuaConst::new(0x20000126);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HARD_BREAK_ENABLED: LuaConst = LuaConst::new(0x20000127);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HAS_CATCH: LuaConst = LuaConst::new(0x20000128);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_PERFECT_WAVEDASH: LuaConst = LuaConst::new(0x20000129);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_READY_GO: LuaConst = LuaConst::new(0x2000012A); //Returns false for exactly one frame after is_ready_go becomes true, used to initiate certain events exactly once at the start of a match
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_DISABLE: LuaConst = LuaConst::new(0x2000012B);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_DISABLE: LuaConst = LuaConst::new(0x2000012C);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_N_DISABLE: LuaConst = LuaConst::new(0x2000012D);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_S_DISABLE: LuaConst = LuaConst::new(0x2000012E);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_USED_FS: LuaConst = LuaConst::new(0x2000012F); //Flags when you just used a Final Smash in Special Smash
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_ATTACK_DASH_FALL_SPEED_Y_MUL: LuaConst = LuaConst::new(0x641);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_JUMP_SPEED_RATIO: LuaConst = LuaConst::new(0x642);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_SMASH_ATTACK_CHARGE_FRAME: LuaConst = LuaConst::new(0x643);
pub const FIGHTER_INSTANCE_WORK_ID_INT_ATTACK_ANGLE: LuaConst = LuaConst::new(0x100000ED);
pub const FIGHTER_INSTANCE_WORK_ID_INT_CLIFF_ID: LuaConst = LuaConst::new(0x100000EE);
pub const FIGHTER_INSTANCE_WORK_ID_INT_COMMAND_INPUT_TIMER: LuaConst = LuaConst::new(0x100000EF);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FINAL_ZOOM_ATTACKER_ID: LuaConst = LuaConst::new(0x100000F0);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FINAL_ZOOM_COUNTER: LuaConst = LuaConst::new(0x100000F1);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FINAL_ZOOM_DEFENDER_ID: LuaConst = LuaConst::new(0x100000F2);
pub const FIGHTER_INSTANCE_WORK_ID_INT_GLIDE_TIMER: LuaConst = LuaConst::new(0x100000F3);
pub const FIGHTER_INSTANCE_WORK_ID_INT_GOT_HIT: LuaConst = LuaConst::new(0x100000F4); //Tracks if a player got hit during One-Hit mode
pub const FIGHTER_INSTANCE_WORK_ID_INT_MASHING: LuaConst = LuaConst::new(0x100000F5);
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRIED: LuaConst = LuaConst::new(0x100000F6);
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRY_TIMER: LuaConst = LuaConst::new(0x100000F7);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_BREAK_TIMER: LuaConst = LuaConst::new(0x100000F8);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_EFFECT_ID: LuaConst = LuaConst::new(0x100000F9);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SPECIAL_ZOOM_GFX: LuaConst = LuaConst::new(0x100000FA);
pub const FIGHTER_STATUS_KIND_SPECIAL_GUARD: LuaConst = LuaConst::new(0x644);