use super::*;

pub const FIGHTER_DEDEDE_INSTANCE_WORK_ID_FLAG_LINK_ITEM_FUSE_BACK: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_DEDEDE_INSTANCE_WORK_ID_INT_LINK_ARROW_FUSE_ITEM: LuaConst = LuaConst::new(0x100000C5);