use super::*;

/*
First Instance Flag: 0x200000F7
First Instance Float: 0x4F
First Instance Int: 0x100000CF
First Status Kind: 0x213
*/

pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_HIGH_POUNCE_ACTIVE: LuaConst = LuaConst::new(0x200000F8);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_SOBAT_TURN: LuaConst = LuaConst::new(0x200000F9);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_MIST_STEP_ACTIVE: LuaConst = LuaConst::new(0x200000FA);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_ELECTRIC_DRAGON_UPPERCUT: LuaConst = LuaConst::new(0x200000FB);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_TO_RAGE_DRIVE: LuaConst = LuaConst::new(0x200000FC);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_TO_HEAVENS_DOOR: LuaConst = LuaConst::new(0x200000FD);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_FLAG_THROW: LuaConst = LuaConst::new(0x200000FE);
pub const FIGHTER_DEMON_INSTANCE_WORK_ID_INT_SPECIAL_N_HOLD_FRAME: LuaConst = LuaConst::new(0x100000D0);
pub const FIGHTER_DEMON_STATUS_KIND_ESCAPE_ATTACK: LuaConst = LuaConst::new(0x214);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_DASH_2: LuaConst = LuaConst::new(0x215);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_DASH_3: LuaConst = LuaConst::new(0x216);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_LW3_CANCEL_ATTACK: LuaConst = LuaConst::new(0x217);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_LW3_EDGE: LuaConst = LuaConst::new(0x218);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_STAND_7: LuaConst = LuaConst::new(0x219);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_STEP_2H: LuaConst = LuaConst::new(0x21A);
pub const FIGHTER_DEMON_STATUS_KIND_ATTACK_STEP_2K: LuaConst = LuaConst::new(0x21B);
pub const FIGHTER_DEMON_STATUS_KIND_CATCH_BACK: LuaConst = LuaConst::new(0x21C);