use super::*;

/*
EDGE:

First Instance Flag: 0x200000F0
First Instance Float: 0x58
First Instance Int: 0x100000CC

EDGE_FLARE2:

First Instance Flag: 0x2000000B

EDGE_FLASH:

First Instance Float: 0x6
First Instance Int: 0x1000000C
*/

pub static mut FIGHTER_EDGE_GENERATE_ARTICLE_ZANSHIN_SHOT: i32 = 5;
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_ESCAPE_AIR_ENABLE_WING: LuaConst = LuaConst::new(0x200000F0);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_ATTACK_AIR_LW_CHARGED: LuaConst = LuaConst::new(0x200000F1);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_BLADE_DASH_EARLY_CANCEL: LuaConst = LuaConst::new(0x200000F2);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_OCTASLASH_PRIME: LuaConst = LuaConst::new(0x200000F3);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_IS_PARRY_FLASH: LuaConst = LuaConst::new(0x200000F4);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_ONE_WINGED_CHANGE: LuaConst = LuaConst::new(0x200000F5);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_HIT_ID: LuaConst = LuaConst::new(0x100000CC);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_ATTACK_COUNT: LuaConst = LuaConst::new(0x100000CD);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_CHARGE_FRAME: LuaConst = LuaConst::new(0x100000CE);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_RETALIATION_CHARGE: LuaConst = LuaConst::new(0x100000CF);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_RETALIATION_CHARGE_TIMER: LuaConst = LuaConst::new(0x100000D0);
pub const FIGHTER_EDGE_STATUS_KIND_WING_ACTIVATE: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_S_CANCEL: LuaConst = LuaConst::new(0x1F5);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_HI_CHARGED_RUSH_WINGED: LuaConst = LuaConst::new(0x1F6);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_LOOP: LuaConst = LuaConst::new(0x1F7);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_PARRY: LuaConst = LuaConst::new(0x1F8);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_PARRY_FLASH: LuaConst = LuaConst::new(0x1F9);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_ATTACK: LuaConst = LuaConst::new(0x1FA);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_ZANSHIN: LuaConst = LuaConst::new(0x1FB);
pub const FIGHTER_EDGE_STATUS_KIND_SPECIAL_LW_APPEAL: LuaConst = LuaConst::new(0x1FC);
pub const FIGHTER_EDGE_SPECIAL_N_XL: LuaConst = LuaConst::new(0x4);
pub const FIGHTER_EDGE_SHIELD_GROUP_KIND_SPECIAL_LW_FLASH: LuaConst = LuaConst::new(0x2);
pub const WEAPON_EDGE_FIRE_STATUS_KIND_FLY_XL: LuaConst = LuaConst::new(0x6);
pub const WEAPON_EDGE_FIRE_STATUS_KIND_BURST_XL: LuaConst = LuaConst::new(0x7);
pub const WEAPON_EDGE_FLARE2_INSTANCE_WORK_ID_FLAG_OWNER_CANCELED: LuaConst = LuaConst::new(0x2000000B);
pub const WEAPON_EDGE_FLASH_INSTANCE_WORK_ID_FLOAT_OPPONENT_POS_X: LuaConst = LuaConst::new(0x6);
pub const WEAPON_EDGE_FLASH_INSTANCE_WORK_ID_FLOAT_OPPONENT_POS_Y: LuaConst = LuaConst::new(0x7);
pub const WEAPON_EDGE_FLASH_INSTANCE_WORK_ID_INT_OPPONENT_OBJECT_ID: LuaConst = LuaConst::new(0x1000000C);

pub const WEAPON_EDGE_ZANSHIN_SHOT_STATUS_KIND_FLY: LuaConst = LuaConst::new(0x0);
pub const WEAPON_EDGE_ZANSHIN_SHOT_STATUS_KIND_VANISH: LuaConst = LuaConst::new(0x1);
pub const WEAPON_EDGE_ZANSHIN_SHOT_STATUS_KIND_HIT: LuaConst = LuaConst::new(0x2);