use super::*;

pub const FIGHTER_EDGE_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_RUSH_CANCEL: LuaConst = LuaConst::new(0x200000F0);
pub const FIGHTER_EDGE_INSTANCE_WORK_ID_INT_ONE_WINGED_SPECIAL_N_DIRECTION: LuaConst = LuaConst::new(0x100000CC);