use super::*;

/*
First Instance Flag: 0x200000E1
First Instance Float: 0x4D
First Instance Int: 0x100000C0
*/

pub const FIGHTER_GANON_GENERATE_ARTICLE_VOLLEY: LuaConst = LuaConst::new(0x2);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLAG_HAS_ACTIVE_VOLLEY: LuaConst = LuaConst::new(0x200000E2);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLAG_SPECIAL_N_CHARGED: LuaConst = LuaConst::new(0x200000E3);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLAG_USED_SPECIAL_N_AIR: LuaConst = LuaConst::new(0x200000E4);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_STARTED_GROUNDED: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_CHARGED: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLOAT_VOLLEY_DAMAGE_CHARGE: LuaConst = LuaConst::new(0x52);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_FLOAT_VOLLEY_SCALE_CHARGE: LuaConst = LuaConst::new(0x53);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_INT_SPECIAL_N_LOOP_COUNT: LuaConst = LuaConst::new(0x100000C1);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_INT_SPECIAL_HI_ROT_ANGLE: LuaConst = LuaConst::new(0x100000C2);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_INT_SPECIAL_HI_MOVE_FRAME: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_INT_SPECIAL_HI_HOLD_FRAME: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_GANON_INSTANCE_WORK_ID_INT_EFFECT_HANDLE: LuaConst = LuaConst::new(0x100000C5);
pub const FIGHTER_GANON_STATUS_KIND_SPECIAL_N_LOOP: LuaConst = LuaConst::new(0x1ED);
pub const FIGHTER_GANON_STATUS_KIND_SPECIAL_N_FIRE: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_GANON_STATUS_KIND_SPECIAL_N_CAPE: LuaConst = LuaConst::new(0x1EF);
pub const FIGHTER_GANON_STATUS_KIND_SPECIAL_HI_MOVE: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_GANON_STATUS_KIND_SPECIAL_HI_END: LuaConst = LuaConst::new(0x1F1);
pub const FIGHTER_GANON_STATUS_KIND_APPEAL_ATTACK: LuaConst = LuaConst::new(0x1F2);
pub const WEAPON_GANON_VOLLEY_STATUS_KIND_FLY: LuaConst = LuaConst::new(0x0);
pub const WEAPON_GANON_VOLLEY_STATUS_KIND_SUMMON: LuaConst = LuaConst::new(0x1);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_FLAG_CHARGED: LuaConst = LuaConst::new(0x2000000A);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_FLOAT_DAMAGE_SCALE: LuaConst = LuaConst::new(0x5);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_FLOAT_SCALE: LuaConst = LuaConst::new(0x6);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_TOTAL_HIT_COUNT: LuaConst = LuaConst::new(0x1000000D);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_FIRST_HIT_ID: LuaConst = LuaConst::new(0x1000000E);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_SECOND_HIT_ID: LuaConst = LuaConst::new(0x1000000F);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_THIRD_HIT_ID: LuaConst = LuaConst::new(0x10000010);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_FOURTH_HIT_ID: LuaConst = LuaConst::new(0x10000011);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_EFFECT_ID_ZERO: LuaConst = LuaConst::new(0x10000012);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_EFFECT_ID_ONE: LuaConst = LuaConst::new(0x10000013);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_EFFECT_ID_TWO: LuaConst = LuaConst::new(0x10000014);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_EFFECT_ID_THREE: LuaConst = LuaConst::new(0x10000015);
pub const WEAPON_GANON_VOLLEY_INSTANCE_WORK_ID_INT_EFFECT_ID_FOUR: LuaConst = LuaConst::new(0x10000016);
pub const WEAPON_GANON_VOLLEY_SHIELD_KIND_BODY: LuaConst = LuaConst::new(0x0);