use super::*;

pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_CAN_ANGLE_CATCH: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_THROW_CRITICAL_ZOOM: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_SPECIAL_S_CANCEL: LuaConst = LuaConst::new(0x200000EE);
pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_SPECIAL_S_FAKE: LuaConst = LuaConst::new(0x200000EF);