use super::*;

pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_CAN_ANGLE_CATCH: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_GAOGAEN_INSTANCE_WORK_ID_FLAG_THROW_CRITICAL_ZOOM: LuaConst = LuaConst::new(0x200000ED);