use super::*;

pub const FIGHTER_GEKKOUGA_GENERATE_ARTICLE_MAT: LuaConst = LuaConst::new(0x4);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_ATTACK_VERTICAL: LuaConst = LuaConst::new(0x200000F1);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_ATTACK_HI: LuaConst = LuaConst::new(0x200000F2);
pub const WEAPON_GEKKOUGA_MAT_STATUS_KIND_FALL: LuaConst = LuaConst::new(0x0);
pub const WEAPON_GEKKOUGA_MAT_SHIELD_KIND_BODY: LuaConst = LuaConst::new(0x0);