use super::*;

pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_DOLL_LINK: LuaConst = LuaConst::new(0x200000F1);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_DOLL_LAUNCH: LuaConst = LuaConst::new(0x200000F2);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_FOUND_DOLL: LuaConst = LuaConst::new(0x200000F3);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_ATTACK_VERTICAL: LuaConst = LuaConst::new(0x200000F4);
pub const FIGHTER_GEKKOUGA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_ATTACK_HI: LuaConst = LuaConst::new(0x200000F5);