use super::*;

pub const FIGHTER_IKE_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_N: LuaConst = LuaConst::new(0x200000E3);
pub const FIGHTER_IKE_GENERATE_ARTICLE_SLASH: LuaConst = LuaConst::new(0x1);
pub const WEAPON_IKE_SLASH_STATUS_KIND_SHOOT: LuaConst = LuaConst::new(0x0);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_FLOAT_BASE_SPEED: LuaConst = LuaConst::new(0x5);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_FLOAT_BASE_POWER: LuaConst = LuaConst::new(0x6);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_FLOAT_ABSORB_SPEED: LuaConst = LuaConst::new(0x7);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_FLOAT_ABSORB_POWER: LuaConst = LuaConst::new(0x8);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_FLAG_ABSORBED_WEAPON: LuaConst = LuaConst::new(0x2000000A);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_INT_EFFECT_HANDLE: LuaConst = LuaConst::new(0x1000000D);
pub const WEAPON_IKE_SLASH_INSTANCE_WORK_ID_INT_TRAIL_HANDLE: LuaConst = LuaConst::new(0x1000000E);
pub const WEAPON_IKE_SLASH_REFLECTOR_KIND_REFLECTOR: LuaConst = LuaConst::new(0x0);