use super::*;

pub const FIGHTER_INKLING_INSTANCE_WORK_ID_FLAG_SPAWN_INK: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_INKLING_INSTANCE_WORK_ID_FLAG_ON_ROLLER_INK: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_INKLING_INSTANCE_WORK_ID_INT_SPAWNED_INK_COUNT: LuaConst = LuaConst::new(0x100000C4);