use super::*;

pub const FIGHTER_KEN_INSTANCE_WORK_ID_FLAG_CAN_KARA_CANCEL: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_KEN_INSTANCE_WORK_ID_INT_ATTACK_COMMAND1_COUNTER: LuaConst = LuaConst::new(0x100000CA);