use super::*;

pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_INPUT: LuaConst = LuaConst::new(0x20000112);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_TEAM_NO: LuaConst = LuaConst::new(0x1000010B);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE: LuaConst = LuaConst::new(0x1000010C);
pub const FIGHTER_KIRBY_STATUS_KIND_SPECIAL_HI5: LuaConst = LuaConst::new(0x37E);