use super::*;

pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_FLAG_WHEEL_RECOIL: LuaConst = LuaConst::new(0x20000112);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_FLAG_FALCON_PUNCH_HIT: LuaConst = LuaConst::new(0x20000113);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_FLOAT_WHEEL_POWER_UP: LuaConst = LuaConst::new(0x70);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_HOLD_TIMER: LuaConst = LuaConst::new(0x1000010B);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_JUMP_COUNT: LuaConst = LuaConst::new(0x1000010C);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_TURN_COUNT: LuaConst = LuaConst::new(0x1000010D);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_FALCON_PUNCH_TURN_COUNT: LuaConst = LuaConst::new(0x1000010E);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE: LuaConst = LuaConst::new(0x1000010F);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_TEAM_NO: LuaConst = LuaConst::new(0x10000110);
pub static mut WHEEL_SPEED_UP: [f32; 8] = [0.0; 8];