use super::*;

pub const FIGHTER_KOOPAJR_INSTANCE_WORK_ID_FLAG_UNIQ_FLOAT: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_KOOPAJR_INSTANCE_WORK_ID_INT_FLOAT_TIME: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_KOOPAJR_STATUS_KIND_FLOAT: LuaConst = LuaConst::new(0x1F0);
pub const WEAPON_KOOPAJR_CANNONBALL_INSTANCE_WORK_ID_FLAG_IS_UP_INPUT: LuaConst = LuaConst::new(0x2000000C);
pub const WEAPON_KOOPAJR_CANNONBALL_INSTANCE_WORK_ID_INT_FREEZE_FRAME: LuaConst = LuaConst::new(0x10000017);