use super::*;

pub const FIGHTER_KROOL_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_JUMP: LuaConst = LuaConst::new(0x200000F5);
pub const FIGHTER_KROOL_INSTANCE_WORK_ID_FLOAT_SPECIAL_LW_CHARGE: LuaConst = LuaConst::new(0x53);
pub const FIGHTER_KROOL_INSTANCE_WORK_ID_INT_SPECIAL_LW_ANGLE: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_KROOL_STATUS_KIND_SPECIAL_LW_CHARGE: LuaConst = LuaConst::new(0x1FA);
pub const FIGHTER_KROOL_STATUS_KIND_SPECIAL_LW_LAUNCH: LuaConst = LuaConst::new(0x1FB);