use super::*;

/*
First Instance Flag: 0x200000EA
First Instance Float: 0x59
First Instance Int: 0x100000C6
*/

pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_URBOSA_FURY: LuaConst = LuaConst::new(0x200000EA);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_SPECIAL_N_MAX_CHARGE: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_JUMP: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_NO_GAIN: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_SPECIAL_N_DEGREE: LuaConst = LuaConst::new(0x59);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_SPECIAL_HI_DEGREE: LuaConst = LuaConst::new(0x5A);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE: LuaConst = LuaConst::new(0x100000C6);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE_ID: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_SPECIAL_HI_CHARGE_FRAME: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_STAMINA: LuaConst = LuaConst::new(0x100000C9);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_SPECIAL_HI_EFFECT_ID_1: LuaConst = LuaConst::new(0x100000CA);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_SPECIAL_HI_EFFECT_ID_2: LuaConst = LuaConst::new(0x100000CB);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_SPECIAL_HI_EFFECT_ID_3: LuaConst = LuaConst::new(0x100000CC);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_SPECIAL_HI_EFFECT_ID_4: LuaConst = LuaConst::new(0x100000CD);
pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_GLIDE_START: LuaConst = LuaConst::new(0x1E9);
pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_LAUNCH: LuaConst = LuaConst::new(0x1EA);
pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_GLIDE: LuaConst = LuaConst::new(0x1EB);
pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_DROP: LuaConst = LuaConst::new(0x1EC);
pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_LAND: LuaConst = LuaConst::new(0x1ED);
pub const FIGHTER_LINK_STATUS_KIND_MORTAL_DRAW_LOOP: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_LINK_STATUS_KIND_MORTAL_DRAW_ATTACK: LuaConst = LuaConst::new(0x1EF);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_ARROW_TYPE: LuaConst = LuaConst::new(0x1000000E);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: LuaConst = LuaConst::new(0x1000000C);
pub const WN_LINK_BOWARROW_NORMAL_ARROW: LuaConst = LuaConst::new(0x0);
pub const WN_LINK_BOWARROW_FIRE_ARROW: LuaConst = LuaConst::new(0x1);
pub const WN_LINK_BOWARROW_SHOCK_ARROW: LuaConst = LuaConst::new(0x2);
pub const WN_LINK_BOWARROW_ICE_ARROW: LuaConst = LuaConst::new(0x3);
pub const WN_LINK_BOWARROW_LIGHT_ARROW: LuaConst = LuaConst::new(0x4);