use super::*;

pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLAG_HAS_STAR: LuaConst = LuaConst::new(0x200000EF);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLAG_USED_AIR_SPECIAL_N: LuaConst = LuaConst::new(0x200000F0);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_FLAG_IS_START_AIR: LuaConst = LuaConst::new(0x200000F1);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLAG_CAN_INPUT_DREAMLAND_EXPRESS: LuaConst = LuaConst::new(0x200000F2);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLAG_DREAMLAND_EXPRESS: LuaConst = LuaConst::new(0x200000F2);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_FLOAT_STAR_DAMAGE: LuaConst = LuaConst::new(0x52);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_INT_STAR_PUNCH_STRENGTH: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_INT_SPECIAL_HELD_TIMER: LuaConst = LuaConst::new(0x100000C5);
pub const FIGHTER_LITTLEMAC_INSTANCE_WORK_ID_INT_SUCCESSFUL_DREAMLAND_EXPRESS_INPUTS: LuaConst = LuaConst::new(0x100000C6);