use super::*;

pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_FLAG_ATTACK_S4_HIT_REFLECT: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_FLAG_DEFENSE_UP: LuaConst = LuaConst::new(0x200000EA);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_FLAG_ACTIVE_PK_FREEZE: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_FLAG_PSI_COUNTER_ATTACKED: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_FLAG_PSI_COUNTER_THROWN: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_INT_DEFENSE_UP_TIMER: LuaConst = LuaConst::new(0x100000C2);
pub const FIGHTER_LUCAS_INSTANCE_WORK_ID_INT_DEFENSE_UP_EFFECT_TIMER: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_LUCAS_STATUS_KIND_SPECIAL_GUARD_BURST: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_LUCAS_STATUS_KIND_SPECIAL_LW_CATCH: LuaConst = LuaConst::new(0x1EF);
pub const FIGHTER_LUCAS_STATUS_KIND_SPECIAL_LW_THROW: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_LUCAS_SHIELD_KIND_SPECIAL_LW_GUARD: LuaConst = LuaConst::new(0x0);
pub const FIGHTER_LUCAS_SHIELD_GROUP_KIND_SPECIAL_LW_GUARD: LuaConst = LuaConst::new(0x2);