use super::*;

pub const FIGHTER_LUCARIO_GENERATE_ARTICLE_BONE: LuaConst = LuaConst::new(0x3);
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_SPECIAL_S_LW_INPUT: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_MAX_AURA: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_INT_AURA_LEVEL: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_LUCARIO_STATUS_KIND_HIGH_JUMP_KICK_START: LuaConst = LuaConst::new(0x1F1);
pub const FIGHTER_LUCARIO_STATUS_KIND_HIGH_JUMP_KICK: LuaConst = LuaConst::new(0x1F2);
pub const FIGHTER_LUCARIO_STATUS_KIND_HIGH_JUMP_KICK_LANDING: LuaConst = LuaConst::new(0x1F3);
pub const FIGHTER_LUCARIO_STATUS_KIND_DASHING_FORCE_PALM: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_LUCARIO_STATUS_KIND_POWER_UP_PUNCH: LuaConst = LuaConst::new(0x1F5);
pub const FIGHTER_LUCARIO_STATUS_KIND_SPECIAL_S_HI: LuaConst = LuaConst::new(0x1F6);
pub const FIGHTER_LUCARIO_STATUS_KIND_SPECIAL_S_LW: LuaConst = LuaConst::new(0x1F7);
pub const FIGHTER_LUCARIO_STATUS_KIND_MEGA_EVOLVE: LuaConst = LuaConst::new(0x1F8);
pub const WEAPON_LUCARIO_LUCARIOM_STATUS_KIND_MEGA_EVOLVE: LuaConst = LuaConst::new(0x5);