use super::*;

pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_VIS_OFF: LuaConst = LuaConst::new(0x200000E3);
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_VIS_ON: LuaConst = LuaConst::new(0x200000E4);
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_S_GRAVITY_ON: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_INPUT_ON: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_FLOAT_SPECIAL_LW_POWER: LuaConst = LuaConst::new(0x4B);
pub const FIGHTER_LUCINA_INSTANCE_WORK_ID_INT_SPECIAL_LW_EFFECT_COUNT: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_HI2: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_LW_LOOP: LuaConst = LuaConst::new(0x1EF);