use super::*;

pub const FIGHTER_LUIGI_STATUS_KIND_SPECIAL_LW_LOOP: LuaConst = LuaConst::new(0x1EF);
pub const FIGHTER_LUIGI_STATUS_KIND_SPECIAL_LW_END: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_S_DISCHARGE_CHANCE: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_LW_THROW_DIRECTION: LuaConst = LuaConst::new(0x100000C5);