use super::*;

pub const FIGHTER_MARIO_GENERATE_ARTICLE_HAMMER: LuaConst = LuaConst::new(0x6);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_FLAG_SPECIAL_N_ATTACK_ACTIVE: LuaConst = LuaConst::new(0x200000E4);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_FLAG_SPECIAL_S_HIT: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_JUMP: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_FLOAT_SPECIAL_S_ATTACK_FRAME: LuaConst = LuaConst::new(0x4F);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_FLOAT_SPECIAL_S_DEGREE: LuaConst = LuaConst::new(0x50);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_INT_SPECIAL_N_HELD_FRAME: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_MARIO_STATUS_KIND_SPECIAL_N_ATTACK: LuaConst = LuaConst::new(0x1E4);
pub const FIGHTER_MARIO_STATUS_KIND_SPECIAL_S_LOOP: LuaConst = LuaConst::new(0x1E5);
pub const FIGHTER_MARIO_STATUS_KIND_SPECIAL_S_BONK: LuaConst = LuaConst::new(0x1E6);
pub const FIGHTER_MARIO_STATUS_KIND_SPECIAL_S_JUMP: LuaConst = LuaConst::new(0x1E7);
pub const FIGHTER_MARIO_STATUS_KIND_SPECIAL_S_LANDING: LuaConst = LuaConst::new(0x1E8);