use super::*;

pub const FIGHTER_METAKNIGHT_GENERATE_ARTICLE_BEAM: LuaConst = LuaConst::new(0x3);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_SHIELD_HIT: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_POWER: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLOAT_SPECIAL_LW_DAMAGE: LuaConst = LuaConst::new(0x4D);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_INT_SPECIAL_LW_EFFECT_HANDLE: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_METAKNIGHT_SHIELD_KIND_SPECIAL_LW_GUARD: LuaConst = LuaConst::new(0x0);
pub const FIGHTER_METAKNIGHT_SHIELD_GROUP_KIND_SPECIAL_LW_GUARD: LuaConst = LuaConst::new(0x2);
pub const WEAPON_METAKNIGHT_BEAM_STATUS_KIND_SHOOT: LuaConst = LuaConst::new(0x0);