use super::*;

pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_FLAG_COUNTER_THROW_IS_LINK: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_FLAG_ARMOR_CRUSHING_THUNDER_KICK_ACTIVE_ARMOR: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_FLAG_ARMOR_CRUSHING_THUNDER_KICK_DASH_CANCEL: LuaConst = LuaConst::new(0x200000EE);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_FLOAT_ARMOR_CRUSHING_THUNDER_KICK_CURRENT_ARMOR: LuaConst = LuaConst::new(0x51);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_FLOAT_ARMOR_CRUSHING_THUNDER_KICK_CURRENT_DAMAGE: LuaConst = LuaConst::new(0x52);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_INT_COUNTER_THROW_OBJECT_ID: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_MIIFIGHTER_INSTANCE_WORK_ID_INT_ARMOR_CRUSHING_THUNDER_KICK_ATTRIBUTE: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_MIIFIGHTER_STATUS_KIND_SPECIAL_N3_RISE: LuaConst = LuaConst::new(0x208);
pub const FIGHTER_MIIFIGHTER_STATUS_KIND_SPECIAL_N3_DIVE: LuaConst = LuaConst::new(0x209);
pub const FIGHTER_MIIFIGHTER_STATUS_KIND_SPECIAL_N3_LAND: LuaConst = LuaConst::new(0x20A);
pub const FIGHTER_MIIFIGHTER_STATUS_KIND_SPECIAL_LW1_CHARGE: LuaConst = LuaConst::new(0x20B);
pub const FIGHTER_MIIFIGHTER_STATUS_KIND_SPECIAL_LW1_ATTACK: LuaConst = LuaConst::new(0x20C);