use super::*;

pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_FLAG_BLURRING_SLASHES_CANCEL: LuaConst = LuaConst::new(0x200000E8);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_FLAG_RENDING_SERRATIONS_TRANSITION_ENABLE: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_FLOAT_GUARD_BREAKER_POWER: LuaConst = LuaConst::new(0x58);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_DIRECTION: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_LIGHT_SHURIKEN_COUNT: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_BLURRING_SLASHES_TIMER: LuaConst = LuaConst::new(0x100000C9);
pub const FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_AIRBORNE_ASSAULT_ANGLE: LuaConst = LuaConst::new(0x100000CA);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_N1_LOOP: LuaConst = LuaConst::new(0x1FA);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_N1_ATTACK: LuaConst = LuaConst::new(0x1FB);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_N2_HOLD: LuaConst = LuaConst::new(0x1FC);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_N2_FIRE: LuaConst = LuaConst::new(0x1FD);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_N3_SLASH: LuaConst = LuaConst::new(0x1FE);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_S2_ATTACK_1: LuaConst = LuaConst::new(0x1FF);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_S2_ATTACK_2: LuaConst = LuaConst::new(0x200);
pub const FIGHTER_MIISWORDSMAN_STATUS_KIND_SPECIAL_S2_ATTACK_3: LuaConst = LuaConst::new(0x201);