use super::*;

pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_ARROW_FUSE_ITEM: LuaConst = LuaConst::new(0x100000D2);
pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_BOOMERANG_FUSE_ITEM: LuaConst = LuaConst::new(0x100000D3);
pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_BOOMERANG_FUSE_ITEM_ID: LuaConst = LuaConst::new(0x100000D4);
pub const FIGHTER_MURABTIO_INSTANCE_WORK_ID_INT_TEAM_NO: LuaConst = LuaConst::new(0x100000D5);