use super::*;

pub const FIGHTER_NESS_INSTANCE_WORK_ID_FLAG_ATTACK_S4_HIT_REFLECT: LuaConst = LuaConst::new(0x200000E4);
pub const FIGHTER_NESS_INSTANCE_WORK_ID_FLAG_OFFENSE_UP: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_NESS_INSTANCE_WORK_ID_INT_OFFENSE_UP_TIMER: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_NESS_INSTANCE_WORK_ID_INT_OFFENSE_UP_EFFECT_TIMER: LuaConst = LuaConst::new(0x100000C1);
pub const FIGHTER_NESS_STATUS_KIND_SPECIAL_GUARD_BURST: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_NESS_SHIELD_KIND_PSI_ATTACK_AIR_F_GUARD: LuaConst = LuaConst::new(0x0);
pub const FIGHTER_NESS_SHIELD_KIND_PSI_ATTACK_AIR_F_2_GUARD: LuaConst = LuaConst::new(0x1);
pub const FIGHTER_NESS_SHIELD_GROUP_KIND_PSI_ATTACK_AIR_F_GUARD: LuaConst = LuaConst::new(0x2);
pub const FIGHTER_NESS_SHIELD_GROUP_KIND_PSI_ATTACK_AIR_F_2_GUARD: LuaConst = LuaConst::new(0x3);