use super::*;

pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLAG_IS_LIGHTWEIGHT: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLAG_IS_LIGHTWEIGHT_BURNOUT: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLAG_JUMP_GLIDE_ACTIVE: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLAG_PARAM_CHANGE: LuaConst = LuaConst::new(0x200000EE);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_INT_LIGHTWEIGHT_TIMER: LuaConst = LuaConst::new(0x100000C2);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_INT_LIGHTWEIGHT_EFFECT_TIMER: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_INT_LIGHTWEIGHT_BURNOUT_TIMER: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_INT_LIGHTWEIGHT_BURNOUT_EFFECT_TIMER: LuaConst = LuaConst::new(0x100000C5);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLOAT_LIGHTWEIGHT_METER_TIMER: LuaConst = LuaConst::new(0x14E);
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLOAT_LIGHTWEIGHT_BURNOUT_METER_TIMER: LuaConst = LuaConst::new(0x14F);
pub const FIGHTER_PALUTENA_STATUS_KIND_SPECIAL_HI_GLIDE: LuaConst = LuaConst::new(0x1EA);
pub const FIGHTER_PALUTENA_STATUS_KIND_SPECIAL_HI_TURN: LuaConst = LuaConst::new(0x1EB);