use super::*;

pub const FIGHTER_ROCKMAN_INSTANCE_WORK_ID_FLAG_ROCK_BUSTER_CHARGING: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_ROCKMAN_INSTANCE_WORK_ID_FLAG_ROCK_BUSTER_CHARGED: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_ROCKMAN_INSTANCE_WORK_ID_FLAG_ROCK_BUSTER_VISUAL: LuaConst = LuaConst::new(0x200000EE);
pub const FIGHTER_ROCKMAN_INSTANCE_WORK_ID_INT_ROCK_BUSTER_CHARGE_FRAME: LuaConst = LuaConst::new(0x100000C5);
pub const FIGHTER_ROCKMAN_STATUS_SPECIAL_N_WORK_ID_FLAG_UP_MOTION: LuaConst = LuaConst::new(0x100000A);