use super::*;

pub const FIGHTER_ROSETTA_INSTANCE_WORK_ID_INT_WORMHOLE_TRANSIT_TIMER: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_ROSETTA_INSTANCE_WORK_ID_FLOAT_WORMHOLE_TRANSIT_START_X: LuaConst = LuaConst::new(0x4E);
pub const FIGHTER_ROSETTA_INSTANCE_WORK_ID_FLOAT_WORMHOLE_TRANSIT_START_Y: LuaConst = LuaConst::new(0x4F);
pub const WEAPON_ROSETTA_TICO_INSTANCE_WORK_ID_FLOAT_WORMHOLE_TRANSIT_START_X: LuaConst = LuaConst::new(0x17);
pub const WEAPON_ROSETTA_TICO_INSTANCE_WORK_ID_FLOAT_WORMHOLE_TRANSIT_START_Y: LuaConst = LuaConst::new(0x18);