use super::*;

pub const FIGHTER_ROY_INSTANCE_WORK_ID_FLAG_SOL_ACTIVE: LuaConst = LuaConst::new(0x200000E2);
pub const FIGHTER_ROY_INSTANCE_WORK_ID_INT_SOL_OBJECT_ID: LuaConst = LuaConst::new(0x100000CC);
pub const FIGHTER_ROY_INSTANCE_WORK_ID_INT_SOL_TIMER: LuaConst = LuaConst::new(0x100000CD);