use super::*;

pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_HAS_VANISHED: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_VANISH_ATTACK: LuaConst = LuaConst::new(0x200000EA);
pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_BACK_HIT: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_INT_VANISH_TIMER: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_INT_SHEIKAH_EYE_TIMER: LuaConst = LuaConst::new(0x100000C9);
pub const FIGHTER_SHEIK_STATUS_KIND_SPECIAL_LW_VANISH_ATTACK: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_SHEIK_STATUS_KIND_SPECIAL_LW_VANISH_CANCEL: LuaConst = LuaConst::new(0x1F5);