use super::*;

pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_FLAG_SPECIAL_S_HIT: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_SHEIK_INSTANCE_WORK_ID_INT_SPECIAL_S_OBJECT_ID: LuaConst = LuaConst::new(0x100000C8);