use super::*;

pub const FIGHTER_SNAKE_INSTANCE_WORK_ID_FLAG_SPECIAL_N_EARLY_END: LuaConst = LuaConst::new(0x200000E2);
pub const FIGHTER_SNAKE_INSTANCE_WORK_ID_INT_ATTACK_S4_COUNT: LuaConst = LuaConst::new(0x100000C2);