use super::*;

pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_BOOST_GRAVITY: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE: LuaConst = LuaConst::new(0x100000C1);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE_DECREASE: LuaConst = LuaConst::new(0x100000C2);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_EFFECT_COUNTER: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_FINAL_SMASH_TIMER: LuaConst = LuaConst::new(0x100000C4);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLOAT_BOOST_SPEED: LuaConst = LuaConst::new(0x4E);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_BOOST: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_EAGLE: LuaConst = LuaConst::new(0x1F5);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_ADVENTURE: LuaConst = LuaConst::new(0x1F6);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_DROP: LuaConst = LuaConst::new(0x1F7);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_BOUNCE: LuaConst = LuaConst::new(0x1F8);
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_TURN: LuaConst = LuaConst::new(0x9);
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL_START: LuaConst = LuaConst::new(0xA);
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL: LuaConst = LuaConst::new(0xB);
pub const WEAPON_SONIC_SUPERSONIC_STATUS_KIND_MOVE_BALL_END: LuaConst = LuaConst::new(0xC);

pub const WEAPON_SONIC_SUPERSONIC_INSTANCE_WORK_ID_FLOAT_X_ACCEL: LuaConst = LuaConst::new(0x6);
pub const WEAPON_SONIC_SUPERSONIC_INSTANCE_WORK_ID_FLOAT_Y_ACCEL: LuaConst = LuaConst::new(0x7);