use super::*;

pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_SPECIAL_N_TARGET_DETECTED: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_SPECIAL_S_RUSH: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_SPECIAL_S_BOOSTED: LuaConst = LuaConst::new(0x200000E7);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_FLOAT_BOOST_VALUE: LuaConst = LuaConst::new(0x4E);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_SPECIAL_N_TIMER: LuaConst = LuaConst::new(0x100000C1);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_SPECIAL_N_COOLDOWN_TIMER: LuaConst = LuaConst::new(0x100000C2);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_SPECIAL_N_SEARCH_MISS_TIMER: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_SONIC_INSTANCE_WORK_ID_INT_SPECIAL_S_ANGLE: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_RUSH: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_SONIC_STATUS_KIND_SPECIAL_S_RUSH_END: LuaConst = LuaConst::new(0x1F5);
pub const WEAPON_SONIC_HOMINGTARGET_INSTANCE_WORK_ID_INT_TARGET_EFFECT_HANDLE: LuaConst = LuaConst::new(0x1000000C);