use super::*;

pub const FIGHTER_TOONLINK_INSTANCE_WORK_ID_FLAG_SHOOT_WIND: LuaConst = LuaConst::new(0x200000EF);
pub const FIGHTER_TOONLINK_INSTANCE_WORK_ID_FLAG_HURRICANE_SLASH_MOVE: LuaConst = LuaConst::new(0x200000F0);
pub const FIGHTER_TOONLINK_INSTANCE_WORK_ID_FLAG_DEKU_LEAF_ACTIVE: LuaConst = LuaConst::new(0x200000F1);
pub const FIGHTER_TOONLINK_STATUS_KIND_SPECIAL_HI_GLIDE: LuaConst = LuaConst::new(0x1F1);
pub const FIGHTER_TOONLINK_STATUS_KIND_SPECIAL_HI_TURN: LuaConst = LuaConst::new(0x1F2);
pub const FIGHTER_TOONLINK_STATUS_KIND_SPECIAL_HI_LAND: LuaConst = LuaConst::new(0x1F3);