use super::*;

pub const FIGHTER_WARIO_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_HIT: LuaConst = LuaConst::new(0x200000E8);
pub const FIGHTER_WARIO_INSTANCE_WORK_ID_FLAG_SWING_DING_MOVE: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_LOOP: LuaConst = LuaConst::new(0x201);
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_JUMP_SQUAT: LuaConst = LuaConst::new(0x202);
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_AIR_LOOP: LuaConst = LuaConst::new(0x203);
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_LANDING: LuaConst = LuaConst::new(0x204);
pub const FIGHTER_WARIO_STATUS_KIND_ATTACK_DASH_END: LuaConst = LuaConst::new(0x205);