use super::*;

unsafe extern "C" fn reset_frame(fighter: &mut L2CFighterCommon) {
	let boma = smash::app::sv_system::battle_object_module_accessor(fighter.lua_state_agent);
	let entry_id = WorkModule::get_int(fighter.module_accessor, *FIGHTER_INSTANCE_WORK_ID_INT_ENTRY_ID) as usize;
	let status_kind = fighter.global_table[STATUS_KIND].get_i32();
	//Death Reset
	if [*FIGHTER_STATUS_KIND_ENTRY, *FIGHTER_STATUS_KIND_DEAD, *FIGHTER_STATUS_KIND_REBIRTH].contains(&status_kind) {
		//Universal
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ASDI_START);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_CONTINUE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_FALL);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_AIR_LANDING);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_ENABLE_GRAVITY);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_DASH_GRAVITY_ENABLED);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_AUTO_COUNTER);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_B_CHECK);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_ADD);
		COUNTERHIT_CHECK[entry_id] = false;
		COUNTERHIT_SUCCESS[entry_id] = false;
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED_PREVENT);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_DID_MAX_JUMP_COUNT);
		FIGHTER_BOOL_1[entry_id] = false;
		FIGHTER_BOOL_2[entry_id] = false;
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_FIGHTER_SPECIAL_STATE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_FULL_SMASH_ATTACK);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_HAS_CATCH);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_HITFLOW);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_HIT_MOVE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_IS_CC);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_SHIELD_SPECIAL);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_HI_DISABLE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_DISABLE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_N_DISABLE);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_SPECIAL_S_DISABLE);
		SPECIAL_WALL_JUMP = false;
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_WAVEDASH);
		WorkModule::set_flag(boma, false, FIGHTER_INSTANCE_WORK_ID_FLAG_USED_FS);
		WorkModule::set_float(boma, 0.0, FIGHTER_INSTANCE_WORK_ID_FLOAT_ATTACK_DASH_FALL_SPEED_Y_MUL);
		WorkModule::set_float(boma, 0.0, FIGHTER_INSTANCE_WORK_ID_FLOAT_DASH_GRAB_SPEED);
		LAST_DAMAGE[entry_id] = 0.0;
		SIZE0[entry_id] = 0.0;
		SIZE1[entry_id] = 0.0;
		SIZE2[entry_id] = 0.0;
		SIZE3[entry_id] = 0.0;
		FULL_HOP_ENABLE_DELAY[entry_id] = 0;
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_GOT_HIT);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_MASHING);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_PARRIED);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_PARRY_TIMER);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_BREAK_TIMER);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_DAMAGE);
		WorkModule::set_int(boma, 0, FIGHTER_INSTANCE_WORK_ID_INT_SPECIAL_ZOOM_GFX);
		//Armstrong
		WorkModule::set_flag(boma, false, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_IS_SPECIAL_S);
		WorkModule::set_flag(boma, false, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLAG_IS_SPECIAL_HI);
		WorkModule::set_int(boma, 0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_INT_CHARGE_FRAME);
		WorkModule::set_float(boma, 0.0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_ARMOR_CHARGE_MULTIPLIER);
		WorkModule::set_float(boma, 0.0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CHARGE_END);
		WorkModule::set_float(boma, 0.0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CHARGE_START);
		WorkModule::set_float(boma, 0.0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_CURRENT_DAMAGE);
		WorkModule::set_float(boma, 0.0, FIGHTER_ARMSTRONG_INSTANCE_WORK_ID_FLOAT_DAMAGE_CHARGE_MULTIPLIER);
		//Kirby
		WorkModule::set_flag(boma, false, FIGHTER_KIRBY_INSTANCE_WORK_ID_FLAG_WHEEL_RECOIL);
		WorkModule::set_float(boma, 0.0, FIGHTER_KIRBY_INSTANCE_WORK_ID_FLOAT_WHEEL_POWER_UP);
		WHEEL_SPEED_UP[entry_id] = 0.0;
		WorkModule::set_int(boma, 0, FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_HOLD_TIMER);
		WorkModule::set_int(boma, 0, FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_JUMP_COUNT);
		WorkModule::set_int(boma, 0, FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_WHEEL_TURN_COUNT);
		//Luigi
		WorkModule::set_flag(boma, false, FIGHTER_LUIGI_INSTANCE_WORK_ID_FLAG_TYPHOON_ACTIVE);
		LUIGI_CYCLONE_RNG[entry_id] = 9;
		//Meta Knight
		WorkModule::set_flag(boma, false, FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_S);
		//Mii Swordfighter
		WorkModule::set_flag(boma, false, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_FLAG_BLURRING_SLASHES_CANCEL);
		WorkModule::set_int(boma, 0, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_AIRBORNE_ASSAULT_ANGLE);
		WorkModule::set_int(boma, 0, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_BLURRING_SLASHES_TIMER);
		WorkModule::set_int(boma, 0, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_DIRECTION);
		WorkModule::set_int(boma, 1, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_INT_LIGHT_SHURIKEN_COUNT);
		WorkModule::set_float(boma, 1.0, FIGHTER_MIISWORDSMAN_INSTANCE_WORK_ID_FLOAT_GUARD_BREAKER_POWER);
		//Pikachu
		WorkModule::set_flag(boma, false, FIGHTER_PIKACHU_INSTANCE_WORK_ID_FLAG_ATTACK_11_DASH);
		WorkModule::set_int(boma, 0, FIGHTER_PIKACHU_INSTANCE_WORK_ID_INT_ATTACK_11_COUNT);
		//Dark Samus
		HAS_FIRE_CHARGE_SHOT[entry_id] = false;
		CHARGE_SHOT_TIMER[entry_id] = 0;
		SAMUSD_X[entry_id] = 0.0;
		SAMUSD_Y[entry_id] = 0.0;
		//Sonic
		WorkModule::set_flag(boma, false, FIGHTER_SONIC_INSTANCE_WORK_ID_FLAG_BOOST_GRAVITY);
		WorkModule::set_int(boma, 0, FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE);
		WorkModule::set_int(boma, 0, FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_GAUGE_DECREASE);
		WorkModule::set_int(boma, 0, FIGHTER_SONIC_INSTANCE_WORK_ID_INT_BOOST_EFFECT_COUNTER);
		WorkModule::set_float(boma, 0.0, FIGHTER_SONIC_INSTANCE_WORK_ID_FLOAT_BOOST_SPEED);
	};
}

//Installation
pub fn install() {
	Agent::new("mario").on_line(Main, reset_frame).install();
	Agent::new("donkey").on_line(Main, reset_frame).install();
	Agent::new("link").on_line(Main, reset_frame).install();
	Agent::new("samus").on_line(Main, reset_frame).install();
	Agent::new("samusd").on_line(Main, reset_frame).install();
	Agent::new("yoshi").on_line(Main, reset_frame).install();
	Agent::new("kirby").on_line(Main, reset_frame).install();
	Agent::new("fox").on_line(Main, reset_frame).install();
	Agent::new("pikachu").on_line(Main, reset_frame).install();
	Agent::new("luigi").on_line(Main, reset_frame).install();
	Agent::new("ness").on_line(Main, reset_frame).install();
	Agent::new("captain").on_line(Main, reset_frame).install();
	Agent::new("purin").on_line(Main, reset_frame).install();
	Agent::new("peach").on_line(Main, reset_frame).install();
	Agent::new("daisy").on_line(Main, reset_frame).install();
	Agent::new("koopa").on_line(Main, reset_frame).install();
	Agent::new("popo").on_line(Main, reset_frame).install();
	Agent::new("nana").on_line(Main, reset_frame).install();
	Agent::new("sheik").on_line(Main, reset_frame).install();
	Agent::new("zelda").on_line(Main, reset_frame).install();
	Agent::new("mariod").on_line(Main, reset_frame).install();
	Agent::new("pichu").on_line(Main, reset_frame).install();
	Agent::new("falco").on_line(Main, reset_frame).install();
	Agent::new("marth").on_line(Main, reset_frame).install();
	Agent::new("lucina").on_line(Main, reset_frame).install();
	Agent::new("younglink").on_line(Main, reset_frame).install();
	Agent::new("ganon").on_line(Main, reset_frame).install();
	Agent::new("mewtwo").on_line(Main, reset_frame).install();
	Agent::new("roy").on_line(Main, reset_frame).install();
	Agent::new("chrom").on_line(Main, reset_frame).install();
	Agent::new("gamewatch").on_line(Main, reset_frame).install();
	Agent::new("metaknight").on_line(Main, reset_frame).install();
	Agent::new("pit").on_line(Main, reset_frame).install();
	Agent::new("pitb").on_line(Main, reset_frame).install();
	Agent::new("szerosuit").on_line(Main, reset_frame).install();
	Agent::new("wario").on_line(Main, reset_frame).install();
	Agent::new("snake").on_line(Main, reset_frame).install();
	Agent::new("ike").on_line(Main, reset_frame).install();
	Agent::new("pzenigame").on_line(Main, reset_frame).install();
	Agent::new("pfushigisou").on_line(Main, reset_frame).install();
	Agent::new("plizardon").on_line(Main, reset_frame).install();
	Agent::new("diddy").on_line(Main, reset_frame).install();
	Agent::new("lucas").on_line(Main, reset_frame).install();
	Agent::new("sonic").on_line(Main, reset_frame).install();
	Agent::new("dedede").on_line(Main, reset_frame).install();
	Agent::new("pikmin").on_line(Main, reset_frame).install();
	Agent::new("lucario").on_line(Main, reset_frame).install();
	Agent::new("robot").on_line(Main, reset_frame).install();
	Agent::new("toonlink").on_line(Main, reset_frame).install();
	Agent::new("wolf").on_line(Main, reset_frame).install();
	Agent::new("murabito").on_line(Main, reset_frame).install();
	Agent::new("rockman").on_line(Main, reset_frame).install();
	Agent::new("wiifit").on_line(Main, reset_frame).install();
	Agent::new("rosetta").on_line(Main, reset_frame).install();
	Agent::new("littlemac").on_line(Main, reset_frame).install();
	Agent::new("gekkouga").on_line(Main, reset_frame).install();
	Agent::new("miifighter").on_line(Main, reset_frame).install();
	Agent::new("miiswordsman").on_line(Main, reset_frame).install();
	Agent::new("miigunner").on_line(Main, reset_frame).install();
	Agent::new("palutena").on_line(Main, reset_frame).install();
	Agent::new("pacman").on_line(Main, reset_frame).install();
	Agent::new("reflet").on_line(Main, reset_frame).install();
	Agent::new("shulk").on_line(Main, reset_frame).install();
	Agent::new("koopajr").on_line(Main, reset_frame).install();
	Agent::new("duckhunt").on_line(Main, reset_frame).install();
	Agent::new("ryu").on_line(Main, reset_frame).install();
	Agent::new("ken").on_line(Main, reset_frame).install();
	Agent::new("cloud").on_line(Main, reset_frame).install();
	Agent::new("kamui").on_line(Main, reset_frame).install();
	Agent::new("bayonetta").on_line(Main, reset_frame).install();
	Agent::new("inkling").on_line(Main, reset_frame).install();
	Agent::new("ridley").on_line(Main, reset_frame).install();
	Agent::new("simon").on_line(Main, reset_frame).install();
	Agent::new("richter").on_line(Main, reset_frame).install();
	Agent::new("krool").on_line(Main, reset_frame).install();
	Agent::new("shizue").on_line(Main, reset_frame).install();
	Agent::new("gaogaen").on_line(Main, reset_frame).install();
	Agent::new("packun").on_line(Main, reset_frame).install();
	Agent::new("jack").on_line(Main, reset_frame).install();
	Agent::new("brave").on_line(Main, reset_frame).install();
	Agent::new("buddy").on_line(Main, reset_frame).install();
	Agent::new("dolly").on_line(Main, reset_frame).install();
	Agent::new("master").on_line(Main, reset_frame).install();
	Agent::new("tantan").on_line(Main, reset_frame).install();
	Agent::new("pickel").on_line(Main, reset_frame).install();
	Agent::new("edge").on_line(Main, reset_frame).install();
	Agent::new("elight").on_line(Main, reset_frame).install();
	Agent::new("eflame").on_line(Main, reset_frame).install();
	Agent::new("demon").on_line(Main, reset_frame).install();
	Agent::new("trail").on_line(Main, reset_frame).install();
	Agent::new("koopag").on_line(Main, reset_frame).install();
}